# Generated by Django 4.2.1 on 2023-05-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentbox', '0016_alter_adscomment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adscomment',
            name='date',
            field=models.CharField(default='2023-05-17', max_length=10),
        ),
    ]
